---
title: "Surdek Activity 7"
author: "msurdek"
date: "2/15/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(width = 100)
```

## read packages

```{r, message=FALSE, warnings=FALSE, results=FALSE}
library(dplyr)
library(readr)
library(rattle)
library(randomForest)
library(rpart)
library(caret)
```

```{r, message=FALSE, warnings=FALSE, results=FALSE}
boston <- read_csv("Hdma.csv") |> 
  mutate(deny = as.factor(deny)) |> 
  select(!...1)
```

```{r}
bostonTREE <- new.env()

evalq({
  data <- boston
  nobs <- nrow(data)
  form <- formula(deny ~ .)
  vars <- names(data)
  set.seed(42)
  train <- sample(nobs, .7 * nobs)
  training <- data[train,]
}, bostonTREE)

bostonRPART <- new.env(parent = bostonTREE)

evalq({
  model <- rpart(formula = form, data = data[train, vars])
}, bostonRPART)
```


```{r}
str(bostonRPART$model)

print(bostonRPART$model)

printcp(bostonRPART$model)

summary(bostonRPART$model)

opar <- par(xpd = TRUE)
plot(bostonRPART$model)
text(bostonRPART$model)
par(opar)
```


```{r}
bostonTREE$pred <- predict(bostonRPART$model, bostonTREE$training, type = "class")

confusionMatrix(bostonTREE$pred, bostonTREE$training$deny)

```

## random forest

```{r}
bostonDS <- new.env()

evalq({
  data <- na.omit(boston)
  nobs <- nrow(data)
  form <- formula(deny ~ .)
  target <- all.vars(form)[1]
  vars <- names(data)
  set.seed(42)
  train <- sample(nobs, .7 * nobs)
  training <- data[train,]
}, bostonDS)

bostonRF <- new.env(parent = bostonDS)

evalq({
  model <- randomForest(formula = form,
                        data = data[train, vars],
                        ntree = 500, mtry = 4,
                        importance = TRUE,
                        localImp =TRUE,
                        replace = FALSE)
}, bostonRF)
```


```{r}
str(bostonRF$model)

head(bostonRF$model$predicted, 10)

head(bostonRF$model$importance)

data.frame(round(bostonRF$model$importance,4)) |> 
  arrange(desc(MeanDecreaseAccuracy))

head(bostonRF$model$localImp)[,1:4]

bostonRF$model$err.rate

round(head(bostonRF$model$err.rate, 15), 4)

evalq({
  min.err <- min(data.frame(model$err.rate)["OOB"])
  min.err.idx <- which(data.frame(model$err.rate)["OOB"] == min.err)
}, bostonRF)

bostonRF$min.err

bostonRF$min.err.idx

bostonRF$model$err.rate[bostonRF$min.err.idx]

head(bostonRF$model$votes)

head(apply(bostonRF$model$votes, 1, sum))

plot(bostonRF$model)

bostonDS$pred <- predict(bostonRF$model, bostonDS$training)

confusionMatrix(bostonDS$pred, bostonDS$training$deny)

```
