---
title: "Surdek Activity 2"
author: "msurdek"
date: "1/11/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## launch rattle

```{r}
library(rattle)
#rattle()
library(magrittr)
library(ggplot2)
```

## Summarize quakes 

```{r}
data(quakes)
names(quakes)
dim(quakes)
```

## Text summary

```{r}
data <- quakes

sw <- capture.output(str(data, vec.len = 1))
swa <- sprintf("%2d", 1:length(sw[-1]))
swa <- paste(swa, sw[-1], sep = "", collapse = "\n")
swa <- gsub("\\.\\.: [0:9]+ [0:9]+ \\.\\.\\.", "..", swa)
swa <- gsub("( \\$|:|)", "", swa)
cat(swa)
```

## 

```{r}
str(data)
```

```{r}
#library(e1071)
library(fBasics)
basicStats(data)
```

```{r}
data %>%
  ggplot(aes(x=lat, y=long)) +
  geom_point()
```





```{r}
library(magrittr) # Utilise %>% and %<>% pipeline operators.

# This log generally records the process of building a model. 
# However, with very little effort the log can also be used 
# to score a new dataset. The logical variable 'building' 
# is used to toggle between generating transformations, 
# when building a model and using the transformations, 
# when scoring a dataset.

building <- TRUE
scoring  <- ! building

# A pre-defined value is used to reset the random seed 
# so that results are repeatable.

crv$seed <- 42 

#=======================================================================
# Rattle timestamp: 2022-01-11 19:21:10 x86_64-w64-mingw32 

# Load an R dataset.

data(list = "quakes", package = "datasets")
crs$dataset <- quakes
names(crs$dataset) <- gsub("-", ".", names(crs$dataset))

#=======================================================================
# Rattle timestamp: 2022-01-11 19:21:11 x86_64-w64-mingw32 

# Action the user selections from the Data tab. 

# Build the train/validate/test datasets.

# nobs=1000 train=700 validate=150 test=150

set.seed(crv$seed)

crs$nobs <- nrow(crs$dataset)

crs$train <- sample(crs$nobs, 0.7*crs$nobs)

crs$nobs %>%
  seq_len() %>%
  setdiff(crs$train) %>%
  sample(0.15*crs$nobs) ->
crs$validate

crs$nobs %>%
  seq_len() %>%
  setdiff(crs$train) %>%
  setdiff(crs$validate) ->
crs$test

# The following variable selections have been noted.

crs$input     <- c("lat", "long", "depth", "mag", "stations")

crs$numeric   <- c("lat", "long", "depth", "mag", "stations")

crs$categoric <- NULL

crs$target    <- NULL
crs$risk      <- NULL
crs$ident     <- NULL
crs$ignore    <- NULL
crs$weights   <- NULL
```


## Plots

```{r}
p01 <- crs %>%
  with(dataset[train,]) %>%
  dplyr::select(depth) %>%
  ggplot2::ggplot(ggplot2::aes(x=depth)) +
  ggplot2::geom_density(lty=3) +
  ggplot2::xlab("depth\n\nRattle 2022-Jan-11 19:21:32 michaelsurdek_snhu") +
  ggplot2::ggtitle("Distribution of depth (sample)") +
  ggplot2::labs(y="Density")

# Display the plots.
install.packages("gridExtra")
gridExtra::grid.arrange(p01)
```

```{r}
p02 <- crs %>%
  with(dataset[train,]) %>%
  dplyr::select(mag) %>%
  ggplot2::ggplot(ggplot2::aes(x=mag)) +
  ggplot2::geom_density(lty=3) +
  ggplot2::xlab("mag\n\nRattle 2022-Jan-11 19:24:56 michaelsurdek_snhu") +
  ggplot2::ggtitle("Distribution of mag (sample)") +
  ggplot2::labs(y="Density")

# Display the plots.

gridExtra::grid.arrange(p02)
```

```{r}
p03 <- crs %>%
  with(dataset[train,]) %>%
  ggplot2::ggplot(ggplot2::aes(y=stations)) +
  ggplot2::geom_boxplot(ggplot2::aes(x="All"), notch=TRUE, fill="grey") +
  ggplot2::stat_summary(ggplot2::aes(x="All"), fun.y=mean, geom="point", shape=8) +
  ggplot2::xlab("Rattle 2022-Jan-11 19:29:02 michaelsurdek_snhu") +
  ggplot2::ggtitle("Distribution of stations (sample)") +
  ggplot2::theme(legend.position="none")

# Display the plots.

gridExtra::grid.arrange(p03)
```

```{r}
p04 <- crs %>%
  with(dataset[train,]) %>%
  dplyr::select(stations) %>%
  ggplot2::ggplot(ggplot2::aes(x=stations)) +
  ggplot2::geom_density(lty=3) +
  ggplot2::xlab("stations\n\nRattle 2022-Jan-11 19:30:12 michaelsurdek_snhu") +
  ggplot2::ggtitle("Distribution of stations (sample)") +
  ggplot2::labs(y="Density")

# Display the plots.

gridExtra::grid.arrange(p04)
```


```{r}
p05 <- crs %>%
  with(dataset[train,]) %>%
  ggplot2::ggplot(ggplot2::aes(y=mag)) +
  ggplot2::geom_boxplot(ggplot2::aes(x="All"), notch=TRUE, fill="grey") +
  ggplot2::stat_summary(ggplot2::aes(x="All"), fun.y=mean, geom="point", shape=8) +
  ggplot2::xlab("Rattle 2022-Jan-11 19:31:26 michaelsurdek_snhu") +
  ggplot2::ggtitle("Distribution of mag (sample)") +
  ggplot2::theme(legend.position="none")

# Display the plots.

gridExtra::grid.arrange(p05)
```










