---
title: "Surdek Milestone Two Scrap"
author: "msurdek"
date: "9/6/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(width = 100)
```

```{r, message=FALSE, warnings=FALSE, results=FALSE}
library(dplyr)
library(ggplot2)
library(tidymodels)
library(recipes)
library(forcats)
library(tidytext)
#install.packages("tidymodels")
library(readr)
library(pastecs)
library(moments)
```

```{r}
churn_data <- read_csv("/home/msurdek/Documents/School/SNHU/DAT 690 Capstone in Data Analytics/Assignments/Project/Data/Churn Data.csv") |> 
  mutate(CHURN = as.factor(CHURN)) |> 
  rename(PRZM_NUM = 'Column 45') |> 
  mutate(CSA_main = substr(CSA,1,3))

data <- churn_data |>
  select(!c(CHURNDEP)) |> 
  select(!c(CREDIT_RATING)) |> 
  select(!c(PRZM_NUM)) |> 
  select(!c(OCC, OCC_LABEL)) |> 
  select(!c(MARRY,MARRY_LABEL)) |> 
  select(!c(CSA,CSA_main)) |>
  select(c(CUSTOMER, CHURN,MOU,DIRECTAS,OVERAGE,ROAM,CHANGEM,DROPVCE,BLCKVCE,UNANSVCE,THREEWAY,MOUREC,OUTCALLS,INCALLS,PEAKVCE,OPEAKVCE,DROPBLK,CALLFWDV,CALLWAIT)) |> 
  na.omit()


#select(c(REVENUE,MOU,RECCHRGE,DIRECTAS,OVERAGE,ROAM,CHANGEM,CHANGER,DROPVCE,BLCKVCE,UNANSVCE,THREEWAY,MOUREC,OUTCALLS,INCALLS,PEAKVCE,OPEAKVCE,DROPBLK,CALLFWDV,CALLWAIT,CSA_main)) |> 


pca_rec <- recipe(~., data = data) %>%
  update_role(CUSTOMER, CHURN, new_role = "id") %>%
  step_normalize(all_predictors()) %>%
  step_pca(all_predictors())

pca_prep <- prep(pca_rec)

pca_prep

#summary(data)
```



```{r, fig.height=15}
  tidied_pca <- tidy(pca_prep, 2)

tidied_pca %>%
  filter(component %in% paste0("PC", 1:5)) %>%
  mutate(component = fct_inorder(component)) %>%
  ggplot(aes(value, terms, fill = terms)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~component, nrow = 1) +
  labs(y = NULL)
```

```{r}

tidied_pca %>%
  filter(component %in% paste0("PC", 1:4)) %>%
  group_by(component) %>%
  top_n(8, abs(value)) %>%
  ungroup() %>%
  mutate(terms = reorder_within(terms, abs(value), component)) %>%
  ggplot(aes(abs(value), terms, fill = value > 0)) +
  geom_col() +
  facet_wrap(~component, scales = "free_y") +
  scale_y_reordered() +
  labs(
    x = "Absolute value of contribution",
    y = NULL, fill = "Positive?"
  )

```

```{r}
juice(pca_prep) %>%
  ggplot(aes(PC1, PC2)) +
  geom_point(aes(color = CHURN), alpha = 0.7, size = 2) +
  labs(color = NULL)
```