---
title: "Surdek Milestone Three"
author: "msurdek"
date: "9/22/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(width = 100)
```

```{r, message=FALSE, warnings=FALSE, results=FALSE}
library(dplyr)
library(ggplot2)
library(tidymodels)
library(recipes)
library(forcats)
library(tidytext)
library(readr)
library(pastecs)
library(moments)
library(corrplot)
library(car)
library(janitor)
library(caret)
```

## read data

```{r}
churn_data <- read_csv("/home/msurdek/Documents/School/SNHU/DAT 690 Capstone in Data Analytics/Assignments/Project/Data/Churn Data.csv") |> 
  mutate(CHURN = as.factor(CHURN)) |> 
  rename(PRZM_NUM = 'Column 45') |> 
  mutate(CSA_main = substr(CSA,1,3))

#5
id_vars <- c('CUSTOMER','CHURNDEP','CALIBRAT','OCC','MARRY')
#1
target_vars <- c('CHURN')
#16
usage_vars <- c('MOU','OVERAGE','ROAM','CHANGEM','UNANSVCE','THREEWAY','MOUREC','OUTCALLS','INCALLS','PEAKVCE','OPEAKVCE','CALLFWDV','CALLWAIT','NEWCELLY','NEWCELLN')
#2
coverage_vars <- c('DROPVCE','DROPBLK','BLCKVCE')
#6
sub_vars <- c('REVENUE','RECCHRGE','CHANGER','MONTHS','UNIQSUBS','ACTVSUBS')
#9
service_vars <- c('DIRECTAS','CUSTCARE','MAILORD','MAILRES','MAILFLAG','RETCALLS','RETACCPT','REFER','RETCALL')
#7
eq_vars <- c('PHONES','MODELS','EQPDAYS','REFURB','WEBCAP','SETPRCM','SETPRC')
#4
dem_vars_label <- c('CREDIT_RATING','PRZM_NUM','OCC_LABEL','MARRY_LABEL')
#20
dem_vars_dich <- c('CREDITA', 'CREDITAA', 'CREDITB', 'CREDITC', 'CREDITDE', 'CREDITGY', 'CREDITZ', 'PRIZMRUR', 'PRIZMUB', 'PRIZMTWN', 'OCCPROF', 'OCCCLER', 'OCCCRFT', 'OCCSTUD', 'OCCHMKR', 'OCCRET', 'OCCSELF', 'MARRYUN', 'MARRYYES', 'MARRYNO')
#13
dem_vars_other <- c('AGE1','AGE2','CHILDREN','TRUCK','RV','OWNRENT','TRAVEL','PCOWN','CREDITCD','INCMISS','INCOME','MCYCLE','CREDITAD')
#2
location_vars <- c('CSA','CSA_main')

summary(churn_data)
```

## PCA Data

```{r}
pca_data <- churn_data |> 
  select(!CHURNDEP) |> 
  na.omit()

#5
id_pca_vars <- c('CUSTOMER')
#1
target_pca_vars <- c('CHURN')
#16
usage_pca_vars <- c('MOU','OVERAGE','ROAM','CHANGEM','UNANSVCE','THREEWAY','MOUREC','OUTCALLS','INCALLS','PEAKVCE','OPEAKVCE','CALLFWDV','CALLWAIT','NEWCELLY','NEWCELLN')
#2
coverage_pca_vars <- c('DROPVCE','DROPBLK','BLCKVCE')
#6
sub_pca_vars <- c('REVENUE','RECCHRGE','CHANGER','MONTHS','UNIQSUBS','ACTVSUBS')
#9
service_pca_vars <- c('DIRECTAS','CUSTCARE','MAILORD','MAILRES','MAILFLAG','RETCALLS','RETACCPT','REFER','RETCALL')
#7
eq_pca_vars <- c('PHONES','MODELS','EQPDAYS','REFURB','WEBCAP','SETPRCM','SETPRC')
#4
dem_pca_vars_label <- c('CREDIT_RATING','PRZM_NUM','OCC_LABEL','MARRY_LABEL')
#20
dem_pca_vars_dich <- c('CREDITA', 'CREDITAA', 'CREDITB', 'CREDITC', 'CREDITDE', 'CREDITGY', 'CREDITZ', 'PRIZMRUR', 'PRIZMUB', 'PRIZMTWN', 'OCCPROF', 'OCCCLER', 'OCCCRFT', 'OCCSTUD', 'OCCHMKR', 'OCCRET', 'OCCSELF', 'MARRYUN', 'MARRYYES', 'MARRYNO')
#13
dem_pca_vars_other <- c('AGE1','AGE2','CHILDREN','TRUCK','RV','OWNRENT','TRAVEL','PCOWN','CREDITCD','INCMISS','INCOME','MCYCLE','CREDITAD')
#2
location_pca_vars <- c('CSA','CSA_main')
```

## Usage PCA

```{r}
usage_pca_data <- pca_data |>
  select(c(id_pca_vars,target_pca_vars,usage_pca_vars)) |> 
  na.omit()

pca_rec <- recipe(~., data = usage_pca_data) %>%
  update_role(CUSTOMER, CHURN, new_role = "id") %>%
  step_normalize(all_predictors()) %>%
  step_pca(all_predictors())

pca_prep <- prep(pca_rec)

tidied_pca <- tidy(pca_prep, 2)

tidied_pca %>%
  filter(component %in% paste0("PC", 1:5)) %>%
  mutate(component = fct_inorder(component)) %>%
  ggplot(aes(value, terms, fill = terms)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~component, nrow = 1) +
  labs(y = NULL)

tidied_pca %>%
  filter(component %in% paste0("PC", 1:4)) %>%
  group_by(component) %>%
  top_n(8, abs(value)) %>%
  ungroup() %>%
  mutate(terms = reorder_within(terms, abs(value), component)) %>%
  ggplot(aes(abs(value), terms, fill = value > 0)) +
  geom_col() +
  facet_wrap(~component, scales = "free_y") +
  scale_y_reordered() +
  labs(
    x = "Absolute value of contribution",
    y = NULL, fill = "Positive?"
  )

juice(pca_prep) %>%
  ggplot(aes(PC1, PC2)) +
  geom_point(aes(color = CHURN), alpha = 0.7, size = 2) +
  labs(color = NULL)

usage_pca <- juice(pca_prep) |> 
  rename(USAGEPC1 = "PC1", USAGEPC2 = "PC2", USAGEPC3 = "PC3", USAGEPC4 = "PC4", USAGEPC5 = "PC5")

usage_pca
```

## Coverage PCA

```{r}
coverage_pca_data <- pca_data |>
  select(c(id_pca_vars,target_pca_vars,coverage_pca_vars)) |> 
  na.omit()

pca_rec <- recipe(~., data = coverage_pca_data) %>%
  update_role(CUSTOMER, CHURN, new_role = "id") %>%
  step_normalize(all_predictors()) %>%
  step_pca(all_predictors())

pca_prep <- prep(pca_rec)

tidied_pca <- tidy(pca_prep, 2)

tidied_pca %>%
  filter(component %in% paste0("PC", 1:5)) %>%
  mutate(component = fct_inorder(component)) %>%
  ggplot(aes(value, terms, fill = terms)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~component, nrow = 1) +
  labs(y = NULL)

tidied_pca %>%
  filter(component %in% paste0("PC", 1:4)) %>%
  group_by(component) %>%
  top_n(8, abs(value)) %>%
  ungroup() %>%
  mutate(terms = reorder_within(terms, abs(value), component)) %>%
  ggplot(aes(abs(value), terms, fill = value > 0)) +
  geom_col() +
  facet_wrap(~component, scales = "free_y") +
  scale_y_reordered() +
  labs(
    x = "Absolute value of contribution",
    y = NULL, fill = "Positive?"
  )

juice(pca_prep) %>%
  ggplot(aes(PC1, PC2)) +
  geom_point(aes(color = CHURN), alpha = 0.7, size = 2) +
  labs(color = NULL)

coverage_pca <- juice(pca_prep) |> 
  rename(COVERAGEPC1 = "PC1", COVERAGEPC2 = "PC2", COVERAGEPC3 = "PC3")#, COVERAGEPC4 = "PC4", COVERAGEPC5 = "PC5")

coverage_pca
```

## Subscription PCA

```{r}
sub_pca_data <- pca_data |>
  select(c(id_pca_vars,target_pca_vars,sub_pca_vars)) |> 
  na.omit()

pca_rec <- recipe(~., data = sub_pca_data) %>%
  update_role(CUSTOMER, CHURN, new_role = "id") %>%
  step_normalize(all_predictors()) %>%
  step_pca(all_predictors())

pca_prep <- prep(pca_rec)

tidied_pca <- tidy(pca_prep, 2)

tidied_pca %>%
  filter(component %in% paste0("PC", 1:5)) %>%
  mutate(component = fct_inorder(component)) %>%
  ggplot(aes(value, terms, fill = terms)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~component, nrow = 1) +
  labs(y = NULL)

tidied_pca %>%
  filter(component %in% paste0("PC", 1:4)) %>%
  group_by(component) %>%
  top_n(8, abs(value)) %>%
  ungroup() %>%
  mutate(terms = reorder_within(terms, abs(value), component)) %>%
  ggplot(aes(abs(value), terms, fill = value > 0)) +
  geom_col() +
  facet_wrap(~component, scales = "free_y") +
  scale_y_reordered() +
  labs(
    x = "Absolute value of contribution",
    y = NULL, fill = "Positive?"
  )

juice(pca_prep) %>%
  ggplot(aes(PC1, PC2)) +
  geom_point(aes(color = CHURN), alpha = 0.7, size = 2) +
  labs(color = NULL)

sub_pca <- juice(pca_prep) |> 
  rename(SUBPC1 = "PC1", SUBPC2 = "PC2", SUBPC3 = "PC3", SUBPC4 = "PC4", SUBPC5 = "PC5")

sub_pca
```

## Service PCA

```{r}
service_pca_data <- pca_data |>
  select(c(id_pca_vars,target_pca_vars,service_pca_vars)) |> 
  na.omit()

pca_rec <- recipe(~., data = service_pca_data) %>%
  update_role(CUSTOMER, CHURN, new_role = "id") %>%
  step_normalize(all_predictors()) %>%
  step_pca(all_predictors())

pca_prep <- prep(pca_rec)

tidied_pca <- tidy(pca_prep, 2)

tidied_pca %>%
  filter(component %in% paste0("PC", 1:5)) %>%
  mutate(component = fct_inorder(component)) %>%
  ggplot(aes(value, terms, fill = terms)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~component, nrow = 1) +
  labs(y = NULL)

tidied_pca %>%
  filter(component %in% paste0("PC", 1:4)) %>%
  group_by(component) %>%
  top_n(8, abs(value)) %>%
  ungroup() %>%
  mutate(terms = reorder_within(terms, abs(value), component)) %>%
  ggplot(aes(abs(value), terms, fill = value > 0)) +
  geom_col() +
  facet_wrap(~component, scales = "free_y") +
  scale_y_reordered() +
  labs(
    x = "Absolute value of contribution",
    y = NULL, fill = "Positive?"
  )

juice(pca_prep) %>%
  ggplot(aes(PC1, PC2)) +
  geom_point(aes(color = CHURN), alpha = 0.7, size = 2) +
  labs(color = NULL)

service_pca <- juice(pca_prep) |> 
  rename(SERVICEPC1 = "PC1", SERVICEPC2 = "PC2", SERVICEPC3 = "PC3", SERVICEPC4 = "PC4", SERVICEPC5 = "PC5")

service_pca
```

## Equipment PCA

```{r}
eq_pca_data <- pca_data |>
  select(c(id_pca_vars,target_pca_vars,eq_pca_vars)) |> 
  na.omit()

pca_rec <- recipe(~., data = eq_pca_data) %>%
  update_role(CUSTOMER, CHURN, new_role = "id") %>%
  step_normalize(all_predictors()) %>%
  step_pca(all_predictors())

pca_prep <- prep(pca_rec)

tidied_pca <- tidy(pca_prep, 2)

tidied_pca %>%
  filter(component %in% paste0("PC", 1:5)) %>%
  mutate(component = fct_inorder(component)) %>%
  ggplot(aes(value, terms, fill = terms)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~component, nrow = 1) +
  labs(y = NULL)

tidied_pca %>%
  filter(component %in% paste0("PC", 1:4)) %>%
  group_by(component) %>%
  top_n(8, abs(value)) %>%
  ungroup() %>%
  mutate(terms = reorder_within(terms, abs(value), component)) %>%
  ggplot(aes(abs(value), terms, fill = value > 0)) +
  geom_col() +
  facet_wrap(~component, scales = "free_y") +
  scale_y_reordered() +
  labs(
    x = "Absolute value of contribution",
    y = NULL, fill = "Positive?"
  )

juice(pca_prep) %>%
  ggplot(aes(PC1, PC2)) +
  geom_point(aes(color = CHURN), alpha = 0.7, size = 2) +
  labs(color = NULL)

eq_pca <- juice(pca_prep) |> 
  rename(EQPC1 = "PC1", EQPC2 = "PC2", EQPC3 = "PC3", EQPC4 = "PC4", EQPC5 = "PC5")

eq_pca
```

## Dem Label PCA

```{r}
dem_pca_data_label <- pca_data |>
  select(c(id_pca_vars,target_pca_vars,dem_pca_vars_label)) |> 
  na.omit()

pca_rec <- recipe(~., data = dem_pca_data_label) %>%
  update_role(CUSTOMER, CHURN, new_role = "id") %>%
  step_normalize(all_predictors()) %>%
  step_pca(all_predictors())

#pca_prep <- prep(pca_rec)

#dem_pca_label <- juice(pca_prep) |> 
  #rename(DEMPC1LABEL = "PC1", DEMPC2LABEL = "PC2", DEMPC3LABEL = "PC3", DEMPC4LABEL = "PC4", DEMPC5LABEL = "PC5")

#dem_pca_label
```

## Dem Dich PCA

```{r}
dem_pca_data_dich <- pca_data |>
  select(c(id_pca_vars,target_pca_vars,dem_pca_vars_dich)) |> 
  na.omit()

pca_rec <- recipe(~., data = dem_pca_data_dich) %>%
  update_role(CUSTOMER, CHURN, new_role = "id") %>%
  step_normalize(all_predictors()) %>%
  step_pca(all_predictors())

pca_prep <- prep(pca_rec)

tidied_pca <- tidy(pca_prep, 2)

tidied_pca %>%
  filter(component %in% paste0("PC", 1:5)) %>%
  mutate(component = fct_inorder(component)) %>%
  ggplot(aes(value, terms, fill = terms)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~component, nrow = 1) +
  labs(y = NULL)

tidied_pca %>%
  filter(component %in% paste0("PC", 1:4)) %>%
  group_by(component) %>%
  top_n(8, abs(value)) %>%
  ungroup() %>%
  mutate(terms = reorder_within(terms, abs(value), component)) %>%
  ggplot(aes(abs(value), terms, fill = value > 0)) +
  geom_col() +
  facet_wrap(~component, scales = "free_y") +
  scale_y_reordered() +
  labs(
    x = "Absolute value of contribution",
    y = NULL, fill = "Positive?"
  )

juice(pca_prep) %>%
  ggplot(aes(PC1, PC2)) +
  geom_point(aes(color = CHURN), alpha = 0.7, size = 2) +
  labs(color = NULL)

dem_pca_dich <- juice(pca_prep) |> 
  rename(DEMPC1DICH = "PC1", DEMPC2DICH = "PC2", DEMPC3DICH = "PC3", DEMPC4DICH = "PC4", DEMPC5DICH = "PC5")

dem_pca_dich
```

## Dem Other PCA

```{r}
dem_pca_data_other <- pca_data |>
  select(c(id_pca_vars,target_pca_vars,dem_pca_vars_other)) |> 
  na.omit()

pca_rec <- recipe(~., data = dem_pca_data_other) %>%
  update_role(CUSTOMER, CHURN, new_role = "id") %>%
  step_normalize(all_predictors()) %>%
  step_pca(all_predictors())

pca_prep <- prep(pca_rec)

tidied_pca <- tidy(pca_prep, 2)

tidied_pca %>%
  filter(component %in% paste0("PC", 1:5)) %>%
  mutate(component = fct_inorder(component)) %>%
  ggplot(aes(value, terms, fill = terms)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~component, nrow = 1) +
  labs(y = NULL)

tidied_pca %>%
  filter(component %in% paste0("PC", 1:4)) %>%
  group_by(component) %>%
  top_n(8, abs(value)) %>%
  ungroup() %>%
  mutate(terms = reorder_within(terms, abs(value), component)) %>%
  ggplot(aes(abs(value), terms, fill = value > 0)) +
  geom_col() +
  facet_wrap(~component, scales = "free_y") +
  scale_y_reordered() +
  labs(
    x = "Absolute value of contribution",
    y = NULL, fill = "Positive?"
  )

juice(pca_prep) %>%
  ggplot(aes(PC1, PC2)) +
  geom_point(aes(color = CHURN), alpha = 0.7, size = 2) +
  labs(color = NULL)

dem_pca_other <- juice(pca_prep) |> 
  rename(DEMPC1OTHER = "PC1", DEMPC2OTHER = "PC2", DEMPC3OTHER = "PC3", DEMPC4OTHER = "PC4", DEMPC5OTHER = "PC5")

dem_pca_other
```


```{r}
pca_model_data <- usage_pca |> 
  left_join(coverage_pca, by = 'CUSTOMER') |> 
  left_join(sub_pca, by = 'CUSTOMER') |> 
  left_join(service_pca, by = 'CUSTOMER') |> 
  left_join(eq_pca, by = 'CUSTOMER') |> 
  left_join(dem_pca_dich, by = 'CUSTOMER') |> 
  left_join(dem_pca_other, by = 'CUSTOMER')

pca_model_data
```

## Logistic Regression Model

```{r}
set.seed(10)

model_data <- churn_data |> 
  select(CUSTOMER,CHURN,REVENUE,MOU,RECCHRGE,MOUREC,PEAKVCE,CALLWAIT,MODELS,EQPDAYS,REFURB,WEBCAP,RETCALL,CSA_main) |> 
  na.omit()

index <- createDataPartition(model_data$CHURN,p=0.75,list=FALSE)
train <- model_data[index,]
data_test_w_cust <- model_data[-index,]
data_test <- data_test_w_cust |> select(!CUSTOMER)

model_data |> tabyl(CHURN)

# data_split <- initial_split(model_data, prop = 0.75, strata = CHURN)
# 
# train <- data_split |> 
#   training() |> 
#   select(!CUSTOMER)
# 
# train |> tabyl(CHURN)
# 
# data_test <- data_split |> 
#   testing()
# 
# data_test |> tabyl(CHURN)

data_train <- upSample(x = train, y = train$CHURN) |> 
  select(!c(Class,CUSTOMER))

data_train |> tabyl(CHURN)

nrow(data_train)
nrow(data_test)

model1<- logistic_reg() %>%
        set_engine("glm") %>%
        set_mode("classification") %>%
        fit(CHURN~., data = data_train)

str(model1)

model <- glm(CHURN ~.,family=binomial(link='logit'),data=data_train)

vif(model)

model_tidied <- tidy(model)
model_tidied

model_tidied_odds <- tidy(model, exponentiate = TRUE)
model_tidied_odds

model_tidied_odds %>%
  filter(p.value < 0.05)


```

## Single Variable Models

```{r}
single_model_data <- churn_data |> 
  select(!c('CHURNDEP','CALIBRAT'))

for(i in colnames(pca_model_data)) {
  set.seed(10)
  data_split <- initial_split(pca_model_data, prop = 0.75, strata = CHURN)

  data_train <- data_split |>
    training()

  data_test <- data_split |>
    testing()

  single_model_df <- data_train |>
    select(c('CHURN',all_of(i))) |>
    na.omit()

  single_model <- logistic_reg() %>%
        set_engine("glm") %>%
        set_mode("classification") %>%
        fit(CHURN~., data = single_model_df)

  model_tidied_odds <- tidy(single_model, exponentiate = TRUE)

  print(i)

  #print(model_tidied_odds)

  print(model_tidied_odds %>%
          filter(term != '(Intercept)') |>
          filter(p.value < 0.1))
}
```




