---
title: "Surdek Milestone Three"
author: "msurdek"
date: "9/22/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(width = 100)
```

```{r, message=FALSE, warnings=FALSE, results=FALSE}
library(dplyr)
library(ggplot2)
library(tidymodels)
library(recipes)
library(forcats)
library(tidytext)
library(readr)
library(pastecs)
library(moments)
library(corrplot)
library(car)
```

## read data

```{r}
churn_data <- read_csv("/home/msurdek/Documents/School/SNHU/DAT 690 Capstone in Data Analytics/Assignments/Project/Data/Churn Data.csv") |> 
  mutate(CHURN = as.factor(CHURN)) |> 
  rename(PRZM_NUM = 'Column 45') |> 
  mutate(CSA_main = substr(CSA,1,3))

#5
id_vars <- c('CUSTOMER','CHURNDEP','CALIBRAT','OCC','MARRY')
#1
target_vars <- c('CHURN')
#16
usage_vars <- c('MOU','OVERAGE','ROAM','CHANGEM','UNANSVCE','THREEWAY','MOUREC','OUTCALLS','INCALLS','PEAKVCE','OPEAKVCE','CALLFWDV','CALLWAIT','NEWCELLY','NEWCELLN')
#2
coverage_vars <- c('DROPVCE','DROPBLK','BLCKVCE')
#6
sub_vars <- c('REVENUE','RECCHRGE','CHANGER','MONTHS','UNIQSUBS','ACTVSUBS')
#9
service_vars <- c('DIRECTAS','CUSTCARE','MAILORD','MAILRES','MAILFLAG','RETCALLS','RETACCPT','REFER','RETCALL')
#7
eq_vars <- c('PHONES','MODELS','EQPDAYS','REFURB','WEBCAP','SETPRCM','SETPRC')
#4
dem_vars_label <- c('CREDIT_RATING','PRZM_NUM','OCC_LABEL','MARRY_LABEL')
#20
dem_vars_dich <- c('CREDITA', 'CREDITAA', 'CREDITB', 'CREDITC', 'CREDITDE', 'CREDITGY', 'CREDITZ', 'PRIZMRUR', 'PRIZMUB', 'PRIZMTWN', 'OCCPROF', 'OCCCLER', 'OCCCRFT', 'OCCSTUD', 'OCCHMKR', 'OCCRET', 'OCCSELF', 'MARRYUN', 'MARRYYES', 'MARRYNO')
#13
dem_vars_other <- c('AGE1','AGE2','CHILDREN','TRUCK','RV','OWNRENT','TRAVEL','PCOWN','CREDITCD','INCMISS','INCOME','MCYCLE','CREDITAD')
#2
location_vars <- c('CSA','CSA_main')

summary(churn_data)
```

## exploring NAs

```{r}
qual_data <- churn_data |> 
  filter(is.na(AGE1) | is.na(CHANGEM))

qual_data
```

## Distributions

```{r}
dist_data <- churn_data |> 
  select(!c('CHURNDEP','CALIBRAT'))

for(i in colnames(dist_data)) {
  dist_df <- dist_data |>
    select(c('CHURN',all_of(i))) |> 
    na.omit()
  plot <- dist_df |> 
    ggplot(aes_string(x=names(dist_df)[2],color='CHURN')) +
    geom_density()
  print(plot)
}
```

## Data Sets

```{r}
data <- churn_data |>
  select(c(target_vars,usage_vars,coverage_vars,sub_vars,service_vars,eq_vars,dem_vars_label,dem_vars_other)) |> 
  na.omit()

model_data <- churn_data |> 
select(c('CUSTOMER',target_vars,usage_vars,'DROPBLK',sub_vars,service_vars,eq_vars,dem_vars_label,dem_vars_other)) |> 
  na.omit()

all_data <- churn_data |>
  select(c(target_vars,usage_vars,coverage_vars,sub_vars,service_vars,eq_vars,dem_vars_label,dem_vars_other))

summary(all_data)

cor_data <- churn_data |>
  select(c(usage_vars,coverage_vars,sub_vars,service_vars,eq_vars,dem_vars_dich,dem_vars_other)) |> 
  na.omit()

pca_data <- churn_data |>
  select(c(id_vars,target_vars,usage_vars)) |> 
  na.omit()
```

## Correlation

```{r}
pairs_data <- data |> 
  select(c(all_of(target_vars),all_of(sub_vars)))

pairs(pairs_data)
plot

res <- cor_data |> 
  #select(1:40) |>
  cor()

corrplot(res, type = "upper", order = "hclust", 
         tl.col = "black", tl.srt = 45)
```

## PCA

```{r}
pca_rec <- recipe(~., data = pca_data) %>%
  update_role(CUSTOMER, CHURN, new_role = "id") %>%
  step_normalize(all_predictors()) %>%
  step_pca(all_predictors())

pca_prep <- prep(pca_rec)

pca_prep

  tidied_pca <- tidy(pca_prep, 2)

tidied_pca %>%
  filter(component %in% paste0("PC", 1:5)) %>%
  mutate(component = fct_inorder(component)) %>%
  ggplot(aes(value, terms, fill = terms)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~component, nrow = 1) +
  labs(y = NULL)

tidied_pca %>%
  filter(component %in% paste0("PC", 1:4)) %>%
  group_by(component) %>%
  top_n(8, abs(value)) %>%
  ungroup() %>%
  mutate(terms = reorder_within(terms, abs(value), component)) %>%
  ggplot(aes(abs(value), terms, fill = value > 0)) +
  geom_col() +
  facet_wrap(~component, scales = "free_y") +
  scale_y_reordered() +
  labs(
    x = "Absolute value of contribution",
    y = NULL, fill = "Positive?"
  )

juice(pca_prep) %>%
  ggplot(aes(PC1, PC2)) +
  geom_point(aes(color = CHURN), alpha = 0.7, size = 2) +
  labs(color = NULL)
```

## Logistic Regression Model

```{r}
set.seed(10)
data_split <- initial_split(model_data, prop = 0.75, strata = CHURN)

data_train <- data_split |> 
  training() |> 
  select(!CUSTOMER)

data_test <- data_split |> 
  testing()

nrow(data_train)
nrow(data_test)

model1<- logistic_reg() %>%
        set_engine("glm") %>%
        set_mode("classification") %>%
        fit(CHURN~., data = data_train)

model <- glm(CHURN ~.,family=binomial(link='logit'),data=data_train)

vif(model)

model_tidied <- tidy(model)
model_tidied

model_tidied_odds <- tidy(model, exponentiate = TRUE)
model_tidied_odds

model_tidied_odds %>%
  filter(p.value < 0.05)


```

## TRAINING DATA

```{r}
pred_class <- predict(model1,
                      new_data = data_train,
                      type = "class")

pred_class[1:5,]

pred_proba <- predict(model1,
                      new_data = data_train,
                      type = "prob")

pred_proba[1:5,]

pred_results <- data_train %>%
  select(CHURN) %>%
  bind_cols(pred_class, pred_proba)

pred_results[1:5, ]
```

```{r}
conf_mat(pred_results, truth = CHURN,
         estimate = .pred_class)
```

```{r}
custom_metrics <- metric_set(accuracy, sens, yardstick::spec, precision, recall, f_meas, kap, mcc)

custom_metrics(pred_results,
               truth = CHURN,
               estimate = .pred_class)
```

```{r}
roc_auc(pred_results,
        truth = CHURN,
        .pred_0)

pred_results %>%
  roc_curve(truth = CHURN, .pred_0) %>%
  autoplot()
```




## TESTING DATA

```{r}
pred_class <- predict(model1,
                      new_data = data_test,
                      type = "class")

pred_class[1:5,]

pred_proba <- predict(model1,
                      new_data = data_test,
                      type = "prob")

pred_proba[1:5,]

pred_results <- data_test %>%
  select(CUSTOMER,CHURN) %>%
  bind_cols(pred_class, pred_proba)

pred_results[1:10, ]
```

```{r}
conf_mat(pred_results, truth = CHURN,
         estimate = .pred_class)
```

```{r}
custom_metrics <- metric_set(accuracy, sens, yardstick::spec, precision, recall, f_meas, kap, mcc)

custom_metrics(pred_results,
               truth = CHURN,
               estimate = .pred_class)
```

```{r}
roc_auc(pred_results,
        truth = CHURN,
        .pred_0)

pred_results %>%
  roc_curve(truth = CHURN, .pred_0) %>%
  autoplot()
```




